### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by aaroniker** [Sysix/dynao-CMS#10]
- [x] 1 Struktur verwalten ("Inhalt" kann als Unterseite weg) 
- [x] 2 Responsive fertig
- [x] 3 Subnavi Seitennamen ausgeben
- [x] 4 Panels um die ganze Tabellen im Backend
- [x] 5 Nach Update überprüfen
- [x] 6 Frontend Ausgabe
- [x] 7 Sprache
- [x] 8 Slots
- [x] 9 metainfos als extension einfügen
- [x] 10 Struktur-Page editieren
- [x] 11 autofocus hinzufügen
- [x] 12 Username/Passwort bei User darf nicht leer sein
- [x] 13 AddonConfig speichern/bearbeiten (wie die normale Config)
- [x] 14 addSecSubnavi
- [x] 15 autoload noch PSR-0 einbeziehen
- [x] 16 formMedialist
- [x] 17 addLinkField 
- [x] 18 addLinklistField
- [x] 19 BG für Responsive
- [x] 20 addon's help site
- [x] 21 Userrechte
- [x] 22 Metainfos als secondnavi
- [x] 23 DYN_MEDIA, DYN_MEDIA_LIST, DYN_LINK, DYN_LINK_LIST
- [x] 24 media im metainfos
- [x] 25 Extensions einfügen
- [x] 26 Einstellungen
- [x] 27 Cache für einzelne Seiten
- [x] 28 AddonNavi CSS
- [x] 29 mehrere Unterseiten im Templates (wird pro datei definiert)
- [x] 30 Installation
- [x] 31 Dashboard (News auslesen)
- [x] 32 Navigation ausgeben (frontend)
- [x] 33 2 Module für Text und Überschrift mit der Installation mitliefern, damit man auch ohne Kenntnisse Content anlegen kann
- [x] 34 Addons -> Weitere Addons (auslesen)

Sonstiges:
- [x] templates/default/config.json Addons den Template vorraussetzen
- [x] templates/default/config.json Slots automatisch hinzufügen
- [x] templates/default/config.json Module (input, output) und Slots per Funktion hinzufügen
- [x] templates/default/config.json Module den Slots zuordnen
