### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by aaroniker** [Sysix/dynao-CMS#13]
System:
- [x] Installer Passwort 2-Mal eingeben wegen Tippfehler
- [ ] CSRF Lücke: http://dynao.de/forum/Thread-Sicherheitsl%C3%BCcke-entdeckt?pid=665#pid665 (mit Modals abfragen)
- [ ] Tooltip für Bildervorschau in Medienmanager // imagemanager
- [ ] Updatefunktion (evtl auch Plugins - s. Wordpress) <- vorerst nicht sooo wichtig
- [x] Fehlende Übersetzungen: http://dynao.de/forum/Thread-Fehlende-%C3%9Cbersetzung?pid=#pid
- [ ] Repeater innerhalb eines Moduls : http://www.advancedcustomfields.com/add-ons/repeater-field/
- [ ] Mehrsprachigkeit // language branch
- [ ] Addons von Addons -> Plugins // plugins branch
- [ ] Addon deinstallieren => Überprüfen ob andere Addons dieses brauchen
- [ ] Socket Verbindung bevorzogen

---

Vorschläge einfach editieren und drunterschreiben!

**Comment by tbaddade** [comment]
ein Verweis auf das Eltern CMS **REDAXO** wäre angebracht ;)

**Comment by Sysix** [comment]
Ujh^^ ein schlauer :)
Du liegst richtig, aber dynaoCMS geht eher seinen eigenen Weg :)
Ein Vermerk irgendwo in der README würde ja reichen^^?
